### PR TITLE
Fix upgrade.sh to match tarball file structure

### LINKED ISSUE #1: upgrade.sh does not match backup file structure
the following directories are not restored correctly:
1. `/etc/ros/$ROSDISTRO/ros.d`  reason: directory may not exist
2. `/usr/sbin`  reason: the upgrade script expects the `sbin` directory to be in the root directory of the tarball, when it is actually a subdirectory of `usr`
3. `/etc/udev/rules.d`  reason: missing `-r` flag

### PR DESCRIPTION
**Pull request by sarcasticnature**
Fixes #1

### CODE REVIEW

File: upgrade.sh [hunk 1]
```diff
@@ -209,15 +209,16 @@ then
   if [ -d ros.d ];
   then
     echo "Restoring Bringup"
+    sudo mkdir -p /etc/ros/$ROSDISTRO/ros.d
```
Comment (civerachb-cpr) [inline upgrade.sh:212]: Before creating the directory, can you please check if the directory exists or not?  If the script is run on a robot that already has ROS configured this may crash if that directory already exists on-disk.

**Review by civerachb-cpr — CHANGES_REQUESTED** [review]

File: upgrade.sh (hunk 1 above)
Comment (sarcasticnature) [reply upgrade.sh:212]: Correct me if I'm wrong, but I believe the `-p` flag should prevent `mkdir` from throwing an error if the directory already exists.  I just ran the command on a Husky where `/etc/ros/melodic/ros.d` already exists w/o issue, is there some other way I should confirm?

Comment (civerachb-cpr) [reply upgrade.sh:212]: :facepalm: yes, you are correct. I'm having a bad brain morning, apparently.

**Review by civerachb-cpr — APPROVED** [review]
